spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:VerticalRelevance/Container-Orchestration-Foundation-Blueprint.git
    targetRevision: dev
    path: ./charts
