spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:VerticalRelevance/Container-Orchestration-Foundation-Blueprint.git
    targetRevision: deploy-test
    path: ./charts
backendRepoUrl: 899456967600.dkr.ecr.us-east-2.amazonaws.com/spring-backend
frontendRepoUrl: 899456967600.dkr.ecr.us-east-2.amazonaws.com/spring-frontend
