replicaCount: 1
image:
  repository: 899456967600.dkr.ecr.us-east-2.amazonaws.com/spring-frontend
  tag: dev-amd64
  pullPolicy: Always
env:
  react_app_api_base_url: https://polling-api.verticalrelevancelabs.com/api
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:899456967600:certificate/d55ce7b5-4d70-4349-b9ec-f85a4714389b
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: polling.verticalrelevancelabs.com
  path: /
  host: polling.verticalrelevancelabs.com
  hosts:
    - chart-example.local
  tls: []
resources:
  requests:
    cpu: 100m
    memory: 512Mi
nodeSelector:
  intent: apps
tolerations: []
affinity: {}
