---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: us-east-2
  version: "1.21"
  tags:
    karpenter.sh/discovery: eksworkshop-eksctl 
iam:
  withOIDC: true

iamIdentityMappings:
  - arn: arn:aws:iam::899456967600:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AWSAdministratorAccess_30f517a3940f0385
    groups:
      - system:masters
    username: admin
    noDuplicateARNs: true # prevents shadowing of ARNs

availabilityZones: ["us-east-2a","us-east-2b","us-east-2c"]

karpenter:
  version: 'v0.18.0'
  #createServiceAccount: true # default is false
  #defaultInstanceProfile: 'KarpenterNodeInstanceProfile' # default is to use the IAM instance profile created by eksctl

managedNodeGroups:
- name: manage
  desiredCapacity: 2
  instanceType: t3.small
  privateNetworking: true
  ssh:
    enableSsm: true
- name: web-server 
  desiredCapacity: 3
  instanceType: t3.small
  privateNetworking: true
  ssh:
    enableSsm: true
- name: app-server 
  desiredCapacity: 3
  instanceType: t3.small
  privateNetworking: true
  ssh:
    enableSsm: true

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: 'arn:aws:kms:us-east-2:899456967600:key/a9710be0-df5f-42a3-b4fa-848d4ec71527'
