replicaCount: 3
image:
  repository: 899456967600.dkr.ecr.us-east-2.amazonaws.com/spring-backend
  tag: dev-amd64
  pullPolicy: Always
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc-secretsmanager:mysql://rdsstack-databaseb269d8bb-muyeczvounq1.cluster-cetdtvws2z9p.us-east-2.rds.amazonaws.com:3306/polling?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  - name: SPRING_DATASOURCE_USERNAME
    value: RDSStackDatabaseSecretA3C9F-HzlvOSVpmAYV
  - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
    value: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
  - name: APP_CORS_ALLOWEDORIGINS
    value: https://polling.verticalrelevancelabs.com
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:899456967600:certificate/d55ce7b5-4d70-4349-b9ec-f85a4714389b
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: polling-api.verticalrelevancelabs.com
  path: /
  host: polling-api.verticalrelevancelabs.com
  hosts:
    - chart-example.local
  tls: []
resources:
  requests:
    cpu: 1000m
    memory: 512Mi
nodeSelector:
  intent: apps
tolerations: []
affinity: {}
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 11
  targetCPU: 50
  targetMemory: 50
