replicaCount: 3
image:
  repository: ''
  tag: dev-amd64
  pullPolicy: Always
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc-secretsmanager:mysql://cluster-endpoint:3306/polling?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  - name: SPRING_DATASOURCE_USERNAME
    value: ''
  - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
    value: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
  - name: APP_CORS_ALLOWEDORIGINS
    value: ''
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: ''
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: ''
  path: /
  host: ''
  hosts:
    - chart-example.local
  tls: []
resources:
  requests:
    cpu: 1000m
    memory: 512Mi
nodeSelector:
  intent: apps
tolerations: []
affinity: {}
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 11
  targetCPU: 50
  targetMemory: 50
