apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=899456967600.dkr.ecr.us-east-2.amazonaws.com/spring-backend
    argocd-image-updater.argoproj.io/image-list: api
    argocd-image-updater.argoproj.io/api.update-strategy: digest 
    #argocd-image-updater.argoproj.io/api.platforms: linux/amd64

  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: api
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: {{ .Values.spec.source.path }}/spring-backend
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
