apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: web={{ .Values.frontend-repo-url }}
    argocd-image-updater.argoproj.io/web.update-strategy: digest
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: public
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: {{ .Values.spec.source.path }}/spring-frontend
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
