apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "spring-frontend.fullname" . }}
  labels:
    app: {{ template "spring-frontend.name" . }}
    chart: {{ template "spring-frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ template "spring-frontend.fullname" . }}
              port:
                number: 80

