apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "spring-backend.fullname" . }}
  labels:
    app: {{ template "spring-backend.name" . }}
    chart: {{ template "spring-backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "spring-backend.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "spring-backend.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "spring-backend.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            SPRING_DATASOURCE_URL: jdbc-secretsmanager:mysql://redisstack-databaseb269d8bb-9xsng08ehlpf.cluster-cetdtvws2z9p.us-east-2.rds.amazonaws.com:3306/polling?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
            SPRING_DATASOURCE_USERNAME: RedisStackDatabaseSecretD6D-HLBDPI135oUH
            SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
